### ISSUE TITLE
直接打开exe出错

### ISSUE THREAD

**Issue by chicl3t** [vfp9/VFP-OOP-Report-Designer#1]
![image](https://github.com/user-attachments/assets/66bbb6a4-3d4a-4d0e-8784-3d2dd09b7b46)

**Comment by vfp9** [comment]
CN:你是下载的 β1.0.43_Release_runtime.rar 这个文件吗？
EN:Did you download the file β1.0.43_Release_runtime.rar?

**Comment by chicl3t** [comment]
yes and i have the dll of vfp9 and vfpa installed.

**Comment by vfp9** [comment]
This application don't support VFPA, only VFP9.

You just need to download β1.0.43_Release_runtime.rar and execute the bat file in administrator mode after unzipping.

**Comment by chicl3t** [comment]
![image](https://github.com/user-attachments/assets/049f7586-b2ce-4fc6-b6e2-b4df0e881337)
![image](https://github.com/user-attachments/assets/b31d268f-4158-41a5-8d7d-2d34bb9f824c)

**Comment by vfp9** [comment]
Please describe your operating environment in detail, including operating system version and regional settings. Please make sure that only the VFP9 SP2 7423 version is installed on your system, or that no version of VFP(including VFPA)is installed.

I can't tell the cause of the problem based on the information you've provided so far.

On my own machine it has no problems (WIN10 21H2/WIN11 23H2,  simplified Chinese)
